import * as dotenv from 'dotenv';
dotenv.config();

/**
 * Generates a summary for a study note (PDF or Image) using Gemini 2.5 Flash API.
 * Downloads the file from Cloudinary, encodes it to base64, and sends it to the Gemini API.
 * 
 * @param fileUrl The secure URL of the file stored on Cloudinary
 * @param mimeType The file's MIME type (e.g. application/pdf, image/jpeg, image/png)
 * @returns The markdown formatted summary generated by Gemini
 */
export const generateSummary = async (fileUrl: string, mimeType: string): Promise<string> => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not defined in environment variables.');
  }

  console.log(`[Gemini Service] Fetching note file from: ${fileUrl}`);

  // 1. Download file content from Cloudinary
  const fileResponse = await fetch(fileUrl);
  if (!fileResponse.ok) {
    throw new Error(`Failed to download note file from Cloudinary. Status: ${fileResponse.statusText}`);
  }

  const arrayBuffer = await fileResponse.arrayBuffer();
  const base64Data = Buffer.from(arrayBuffer).toString('base64');

  console.log(`[Gemini Service] File successfully downloaded, size: ${arrayBuffer.byteLength} bytes. Sending to Gemini API...`);

  // 2. Prepare the prompt for educational summary in English
  const prompt = `You are an expert academic assistant.
Please analyze this study note and generate a comprehensive, professional, and highly organized study summary in English.

STRUCTURE:
Use the following structured headings for the summary:

**Key Topics and Core Concepts:** Explain the fundamental topics covered in the note and core definitions in a structured list.
**Critical Formulas and Equations:** List important mathematical, physical, or technical formulas and explain what each variable means. (Skip if there are no formulas without mentioning it).
**Important Nuances and Tips:** Emphasize critical details, common pitfalls, and practical tips that could appear in exams.
**Conclusion and Summary:** Provide a 2-3 sentence concluding summary of the note's general purpose.

Do not include any conversational sentences or introductory/concluding text. Start directly with the first section.`;

  // 3. Make Gemini API Call
  // Using gemini-2.5-flash with explicitly disabled thinking budget to prevent empty candidate reasoning loop crashes on large PDFs
  const geminiEndpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data
            }
          },
          {
            text: prompt
          }
        ]
      }
    ],
    generationConfig: {
      thinkingConfig: {
        thinkingBudget: 0
      }
    }
  };

  const response = await fetch(geminiEndpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(requestBody)
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error(`[Gemini Service] API Error details:`, errorBody);
    throw new Error(`Gemini API returned status ${response.status}: ${response.statusText}`);
  }

  const result = await response.json() as any;

  // Extract the generated text
  const generatedText = result.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!generatedText) {
    console.error('[Gemini Service] Invalid response structure:', JSON.stringify(result));
    throw new Error('Failed to extract generated summary from Gemini API response.');
  }

  console.log('[Gemini Service] Summary successfully generated.');
  return generatedText;
};
